/*
 * Copyright Strimzi authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */
package io.strimzi.operator.common.model;

import io.strimzi.api.kafka.model.common.CertificateExpirationPolicy;
import io.strimzi.certs.CertManager;
import io.strimzi.operator.common.Reconciliation;

import java.util.Map;

/**
 * Represents the Strimzi Clients CA
 */
public class ClientsCa extends Ca {
    /**
     * Creates a ClientsCA instance
     *
     * @param reconciliation        Reconciliation marker
     * @param certManager           Certificate manager instance
     * @param passwordGenerator     Password generator instance
     * @param clientsCaCert         CA public cert
     * @param clientsCaCertGen      Generation of the CA public cert
     * @param clientsCaKey          CA private key and related generation
     * @param clientsCaKeyGen       Generation of the CA private key
     * @param validityDays          Number of days for which the Clients CA certificate should be value
     * @param renewalDays           Number of day before expiration, when the certificate should be renewed
     * @param generateCa            Flag indicating whether the Clients CA should be generated by Strimzi or not
     * @param policy                Policy defining the behavior when the Clients CA expires (renewal or completely replacing the Clients CA)
     */
    public ClientsCa(Reconciliation reconciliation, CertManager certManager, PasswordGenerator passwordGenerator, Map<String, String> clientsCaCert, int clientsCaCertGen,
                     Map<String, String> clientsCaKey, int clientsCaKeyGen,
                     int validityDays, int renewalDays, boolean generateCa, CertificateExpirationPolicy policy) {
        super(reconciliation, certManager, passwordGenerator,
                "clients-ca",
                clientsCaCert, clientsCaCertGen,
                clientsCaKey, clientsCaKeyGen, validityDays, renewalDays, generateCa, policy);
    }

    @Override
    public String caCertGenerationAnnotation() {
        return ANNO_STRIMZI_IO_CLIENTS_CA_CERT_GENERATION;
    }

    @Override
    public String toString() {
        return "clients-ca";
    }

    @Override
    protected String caName() {
        return "Clients CA";
    }
}
